import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = 0;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex w-full items-center justify-between  bg-emerald-900  px-14 py-2 sm:col-span-2">
          <Link
            href="/"
            className="flex flex-col items-center font-mono text-xl font-semibold capitalize text-white transition-colors  hover:text-grey-950"
          >
            <span>Simple</span> book store
          </Link>

          <div className="flex-1">
          <form className="max-w-md mx-auto">   
                <label  className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                <div className="relative">
                    <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                        <svg className="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                    </div>
                    <input type="search" id="default-search" className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-white focus:ring-blue-500 focus:border-blue-500" placeholder="Search Title or Writer" required />
                    <button type="submit" className="text-white absolute end-2.5 bottom-2.5 bg-emerald-700 hover:bg-emerald-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2">Search</button>
                </div>
            </form>
          </div>

          <nav className="flex items-center gap-6  text-white">
            {!userId && (
              <>
                <Link
                  href="/sign-in"
                  className="transition-colors delay-[21ms] hover:text-black-700"
                >
                  Login
                </Link>
                <Link
                  href="/sign-up"
                  className="transition-colors delay-[21ms] hover:text-black-700"
                >
                  Register
                </Link>
              </>
            )}

            {/* <UserButton after /> */}
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}