import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";
import HeaderLogin from "@/components/HeaderLogin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = 0;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex w-full items-center justify-between  bg-emerald-900  px-14 py-2 sm:col-span-2">
          <Link
            href="/"
            className="flex flex-col items-center font-mono text-xl font-semibold capitalize text-white transition-colors  hover:text-grey-950"
          >
            <span>Simple</span> book store
          </Link>

          <div className="flex-1">
          {/* <SearchBar/> */}
          </div>

          <HeaderLogin/>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}